; siob_baud_test.asm — SIO-B baud rate experiment
;
; Tests SIO-B receive at a configurable baud rate by reprogramming
; CTC ch1 and SIO-B WR4 at runtime. Reads directly from the BIOS
; ring buffer (bypassing IOBYTE routing).
;
; The baud rate is selected by the first command-line argument:
;   SIOBBAUD 0   →  38400  (CTC=1,  SIO x16) — baseline
;   SIOBBAUD 1   →  38400  (CTC=16, SIO x1)  — test x1 mode
;   SIOBBAUD 2   →  76800  (CTC=8,  SIO x1)
;   SIOBBAUD 3   → 115200  (CTC=5,  SIO x1, 6.7% error)
;
; Build:  zmac -z siob_baud_test.asm
; Output: zout/siob_baud_test.cim → SIOBBAUD.COM

        .z80
        org     0100h

; Hardware ports
CTC_CH1 equ     0Dh             ; CTC channel 1 (SIO-B baud)
SIO_B_D equ     09h             ; SIO channel B data
SIO_B_C equ     0Bh             ; SIO channel B control

; BIOS BSS — generated by Makefile from bios.elf (do not hardcode)
        include "siob_bios_addrs.inc"

; CP/M
BDOS    equ     0005h
FCB     equ     005Ch           ; default FCB
C_WRITE equ     02h
C_PRINT equ     09h

; Baud rate table: each entry is 3 bytes (ctc_count, wr4_value, rate_idx)
; rate_idx is the MAME RS232_BAUD_xxx index written to trigger file
BAUD_TABLE:
        ; 0: 38400 x16 — CTC count=1, SIO x16 (WR4=0x44) — baseline
        defb    1, 044h, 0Bh   ; RS232_BAUD_38400
        ; 1: 38400 x1  — CTC count=16, SIO x1 (WR4=0x04) — test x1 mode
        defb    16, 004h, 0Bh  ; RS232_BAUD_38400
        ; 2: 76800 x1  — CTC count=8, SIO x1 (WR4=0x04)
        defb    8, 004h, 017h  ; RS232_BAUD_76800
        ; 3: 115200 x1 — CTC count=5, SIO x1 (WR4=0x04), 6.7% error
        defb    5, 004h, 0Dh   ; RS232_BAUD_115200
BAUD_NAMES:
        defw    name_38400x16, name_38400x1, name_76800, name_115200
name_38400x16: defm '38400 x16$'
name_38400x1:  defm '38400 x1$'
name_76800:    defm '76800 x1$'
name_115200:   defm '115200 x1$'

NUM_RATES equ   4

start:
        ; Parse command line: first non-space char after FCB+1 is rate index
        ld      a, (FCB+1)     ; first char of filename arg
        sub     '0'
        jp      c, usage
        cp      NUM_RATES
        jp      nc, usage
        ld      (rate_sel), a

        ; Print banner with selected rate
        ld      de, msg_banner
        ld      c, C_PRINT
        call    BDOS
        ld      a, (rate_sel)
        ld      l, a
        ld      h, 0
        add     hl, hl          ; ×2
        ld      de, BAUD_NAMES
        add     hl, de
        ld      e, (hl)
        inc     hl
        ld      d, (hl)         ; DE = pointer to name string
        ld      c, C_PRINT
        call    BDOS
        call    putcrlf

        ; Look up baud parameters
        ld      a, (rate_sel)
        ld      l, a
        ld      h, 0
        add     hl, hl          ; ×2
        add     hl, hl          ; ×4 (wait, entries are 3 bytes)
        ; Actually: index × 3
        ld      l, a
        ld      h, 0
        ld      d, h
        ld      e, l
        add     hl, hl          ; ×2
        add     hl, de          ; ×3
        ld      de, BAUD_TABLE
        add     hl, de          ; HL = &BAUD_TABLE[rate_sel]
        ld      a, (hl)
        ld      (ctc_count), a
        inc     hl
        ld      a, (hl)
        ld      (wr4_val), a
        inc     hl
        ld      a, (hl)
        ld      (mame_baud), a

        ; Write rate_idx to trigger file so Lua can configure null_modem
        ; (Lua watches for /tmp/siob_baud_rate with the RS232 baud index)
        ; Actually, we'll just write the index as ASCII to /tmp/siob_baud_config
        ; ... can't write files from CP/M. Use a different mechanism:
        ; Write the mame_baud index to a known memory location that Lua reads.
        ; Use address 0x0004 (scratch — CP/M drive byte, but we restore it)

        ; Reprogram CTC ch1 + SIO-B for the selected baud rate
        di

        ; CTC ch1: counter mode, time constant follows, reset
        ld      a, 047h         ; same mode as BIOS default
        out     (CTC_CH1), a
        ld      a, (ctc_count)
        out     (CTC_CH1), a

        ; SIO-B: channel reset + reprogram
        ld      a, 018h         ; WR0 channel reset
        out     (SIO_B_C), a
        ld      a, 002h         ; WR2 select
        out     (SIO_B_C), a
        ld      a, 010h         ; WR2 = interrupt vector base 0x10
        out     (SIO_B_C), a
        ld      a, 004h         ; WR4 select
        out     (SIO_B_C), a
        ld      a, (wr4_val)    ; WR4 = clock mode + 1 stop, no parity
        out     (SIO_B_C), a
        ld      a, 003h         ; WR3 select
        out     (SIO_B_C), a
        ld      a, 0E1h         ; WR3 = 8-bit, auto enables, Rx enable
        out     (SIO_B_C), a
        ld      a, 005h         ; WR5 select
        out     (SIO_B_C), a
        ld      a, 060h         ; WR5 = 8-bit Tx, Tx disabled
        out     (SIO_B_C), a
        ld      a, 001h         ; WR1 select
        out     (SIO_B_C), a
        ld      a, 01Fh         ; WR1 = Rx/Tx/Ext int, status affects vector
        out     (SIO_B_C), a

        ; Flush ring buffer
        xor     a
        ld      (RXHEAD_B), a
        ld      (RXTAIL_B), a

        ei

        ; Print "Ready, waiting..."
        ld      de, msg_ready
        ld      c, C_PRINT
        call    BDOS

        ; Write trigger file with baud index for Lua
        ; We signal readiness by writing the mame_baud index to /tmp/siob_baud_config
        ; ... we can't write files. Instead, the Lua detects "Ready" on screen.

        ; Wait for data (up to 30 seconds)
        ld      hl, rxdata
        ld      b, 128
        ld      de, 1500        ; 1500 × HALT ≈ 30s at 50fps
wait_first:
        ld      a, (RXTAIL_B)
        ld      c, a
        ld      a, (RXHEAD_B)
        cp      c
        jr      nz, read_loop
        ei
        halt
        dec     de
        ld      a, d
        or      e
        jr      nz, wait_first

        ld      de, msg_timeout
        ld      c, C_PRINT
        call    BDOS
        jp      done

read_loop:
        push    bc
        push    hl
.rwait: ld      a, (RXTAIL_B)
        ld      c, a
        ld      a, (RXHEAD_B)
        cp      c
        jr      z, .rwait
        ld      e, c
        ld      d, 0
        ld      hl, RXBUF_B
        add     hl, de
        ld      a, (hl)
        inc     c
        push    af
        ld      a, c
        ld      (RXTAIL_B), a
        pop     af
        pop     hl
        pop     bc
        cp      1Ah             ; ^Z?
        jr      z, read_done
        ld      (hl), a
        inc     hl
        djnz    read_loop

read_done:
        ld      a, 128
        sub     b
        ld      (rxlen), a

        ; Print results
        ld      de, msg_received
        ld      c, C_PRINT
        call    BDOS
        ld      a, (rxlen)
        call    puthex
        ld      de, msg_bytes
        ld      c, C_PRINT
        call    BDOS

        ; Print hex dump (first 32)
        ld      de, msg_data
        ld      c, C_PRINT
        call    BDOS
        ld      hl, rxdata
        ld      a, (rxlen)
        or      a
        jr      z, check
        cp      32
        jr      c, .hcok
        ld      a, 32
.hcok:  ld      b, a
.hdump: ld      a, (hl)
        push    hl
        push    bc
        call    puthex
        ld      e, ' '
        ld      c, C_WRITE
        call    BDOS
        pop     bc
        pop     hl
        inc     hl
        djnz    .hdump
        call    putcrlf

check:
        ; Check for marker
        ld      a, (rxlen)
        cp      19
        jr      c, fail
        ld      hl, rxdata
        ld      de, marker
        ld      b, 19
.cmp:   ld      a, (de)
        cp      (hl)
        jr      nz, fail
        inc     hl
        inc     de
        djnz    .cmp

        ld      de, msg_pass
        ld      c, C_PRINT
        call    BDOS
        jr      done

fail:
        ld      de, msg_fail
        ld      c, C_PRINT
        call    BDOS

done:
        ; Restore SIO-B to 38400 x16 before exit
        di
        ld      a, 047h
        out     (CTC_CH1), a
        ld      a, 1
        out     (CTC_CH1), a
        ld      a, 018h
        out     (SIO_B_C), a
        ld      a, 002h
        out     (SIO_B_C), a
        ld      a, 010h
        out     (SIO_B_C), a
        ld      a, 004h
        out     (SIO_B_C), a
        ld      a, 044h         ; x16 mode
        out     (SIO_B_C), a
        ld      a, 003h
        out     (SIO_B_C), a
        ld      a, 0E1h
        out     (SIO_B_C), a
        ld      a, 005h
        out     (SIO_B_C), a
        ld      a, 060h
        out     (SIO_B_C), a
        ld      a, 001h
        out     (SIO_B_C), a
        ld      a, 01Fh
        out     (SIO_B_C), a
        xor     a
        ld      (RXHEAD_B), a
        ld      (RXTAIL_B), a
        ei
        rst     0

usage:
        ld      de, msg_usage
        ld      c, C_PRINT
        call    BDOS
        rst     0

; ---- Subroutines ----

puthex:
        push    af
        rrca
        rrca
        rrca
        rrca
        call    putnib
        pop     af
putnib:
        and     0Fh
        add     a, '0'
        cp      '9'+1
        jr      c, .out
        add     a, 'A'-'0'-10
.out:   ld      e, a
        ld      c, C_WRITE
        call    BDOS
        ret

putcrlf:
        ld      e, 13
        ld      c, C_WRITE
        call    BDOS
        ld      e, 10
        ld      c, C_WRITE
        call    BDOS
        ret

; ---- Data ----

msg_banner:  defm 'SIO-B baud rate test: $'
msg_ready:   defm 'Ready, waiting for data...',13,10,'$'
msg_timeout: defm 'TIMEOUT',13,10,'$'
msg_received:defm 'Received $'
msg_bytes:   defm ' bytes',13,10,'$'
msg_data:    defm 'Data: $'
msg_pass:    defm 13,10,'SIOB-BAUD-TEST-OK',13,10,'$'
msg_fail:    defm 13,10,'SIOB-BAUD-TEST-FAIL',13,10,'$'
msg_usage:   defm 'Usage: SIOBBAUD n',13,10
             defm '  0 = 38400  (x16, CTC=1)  baseline',13,10
             defm '  1 = 38400  (x1,  CTC=16) test x1',13,10
             defm '  2 = 76800  (x1,  CTC=8)',13,10
             defm '  3 = 115200 (x1,  CTC=5)',13,10,'$'

marker:      defm 'SIOB-IOBYTE-TEST-OK'

rate_sel:    defb 0
ctc_count:   defb 0
wr4_val:     defb 0
mame_baud:   defb 0
rxlen:       defb 0
rxdata:      defs 128
