#!/usr/bin/env python3
"""Build SNIOS.SPR from snios.asm using zmac.

SPR format (as loaded by CPNETLDR):
  Sector 0:      parameter record (128 bytes)
    +1: code length (2 bytes, little-endian)
    +3: data length (2 bytes, little-endian)
  Sector 1:      data sector (128 bytes, read and discarded by loader)
  Sectors 2..N+1: code (padded to 128-byte sectors)
  Following:      relocation bitmap (1 bit per code byte, MSB first)
    bit=1 means the corresponding byte is the HIGH part of a 16-bit
    address that needs the load bias added.

The relocation bitmap is generated by assembling twice at different ORGs
and comparing: any byte that differs is a relocatable address high-byte.
"""

import os
import subprocess
import sys
import math

ZMAC = os.path.join(os.path.dirname(__file__), '..', 'zmac', 'bin', 'zmac')
SRC = os.path.join(os.path.dirname(__file__), 'snios.asm')
OUTDIR = os.path.join(os.path.dirname(__file__), 'zout')

def assemble(src, org, outdir, suffix=''):
    """Assemble at given ORG, return raw binary bytes."""
    # Create a wrapper that sets ORG before including the source
    wrapper = os.path.join(outdir, f'snios_org{org:04X}{suffix}.asm')
    cim = os.path.join(outdir, f'snios_org{org:04X}{suffix}.cim')

    with open(wrapper, 'w') as f:
        f.write(f'\t.Z80\n')
        f.write(f'\tORG\t0{org:04X}H\n')
        f.write(f'\tINCLUDE\tsnios_body.asm\n')

    result = subprocess.run(
        [ZMAC, '-z', '-I', os.path.dirname(src), '-I', outdir,
         wrapper, '-o', cim],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"zmac error (ORG={org:04X}h):", result.stderr, file=sys.stderr)
        sys.exit(1)

    with open(cim, 'rb') as f:
        data = f.read()

    # cim starts at ORG; we need the raw bytes
    return data


def build_spr(code, bitmap, outpath):
    """Package code and bitmap into SPR format.

    SPR layout (as read by CPNETLDR):
      Sector 0:       parameter record (code/data lengths at +1/+3)
      Sector 1:       data sector (read and discarded by CPNETLDR)
      Sectors 2..N:   code bytes immediately followed by bitmap bytes,
                      packed together and padded to 128-byte boundary.

    CPNETLDR reads ceil(code_length/128) sectors into memory at LDTOP,
    then reads the relocation bitmap starting at LDTOP+code_length.
    The bitmap MUST be packed right after the code bytes in the same
    sectors — NOT in separate sectors after padding.
    """
    code_len = len(code)
    data_len = 0

    # Parameter sector (128 bytes, code/data lengths at offset +1)
    param = bytearray(128)
    param[1] = code_len & 0xFF
    param[2] = (code_len >> 8) & 0xFF
    param[3] = data_len & 0xFF
    param[4] = (data_len >> 8) & 0xFF

    # Data sector (128 bytes, always present, ignored by loader)
    data_sector = bytearray(128)

    # Code + bitmap packed together (padded to 128-byte boundary)
    # CPNETLDR loads ceil(code_len/128) sectors, so the bitmap must
    # fit within those sectors starting at offset code_len.
    combined = bytearray(code) + bytearray(bitmap)
    while len(combined) % 128 != 0:
        combined.append(0)

    spr = bytes(param) + bytes(data_sector) + bytes(combined)

    with open(outpath, 'wb') as f:
        f.write(spr)

    return spr


def main():
    os.makedirs(OUTDIR, exist_ok=True)

    # Create body file (snios.asm without ORG directive)
    # Read the source and strip the ORG line
    with open(SRC, 'r') as f:
        lines = f.readlines()

    body_path = os.path.join(OUTDIR, 'snios_body.asm')
    with open(body_path, 'w') as f:
        for line in lines:
            stripped = line.strip().upper()
            if stripped.startswith('ORG') or stripped.startswith('.Z80'):
                continue  # Skip ORG and .Z80 (set by wrapper)
            f.write(line)

    # Assemble at ORG 0000h and ORG 0100h
    code_0000 = assemble(SRC, 0x0000, OUTDIR)
    code_0100 = assemble(SRC, 0x0100, OUTDIR, '_hi')

    if len(code_0000) != len(code_0100):
        print(f"Size mismatch: ORG=0 → {len(code_0000)}, "
              f"ORG=100h → {len(code_0100)}", file=sys.stderr)
        sys.exit(1)

    code_len = len(code_0000)
    print(f"SNIOS code: {code_len} bytes")

    # Build relocation bitmap by comparing the two assemblies
    # Any byte that differs by exactly 1 (the page difference) is relocatable
    bitmap_bits = []
    reloc_count = 0
    for i in range(code_len):
        diff = code_0100[i] - code_0000[i]
        if diff == 1:  # High byte differs by 1 page
            bitmap_bits.append(1)
            reloc_count += 1
        elif diff == 0:
            bitmap_bits.append(0)
        else:
            print(f"WARNING: byte {i:04X} differs by {diff} "
                  f"(0x{code_0000[i]:02X} vs 0x{code_0100[i]:02X})",
                  file=sys.stderr)
            bitmap_bits.append(0)

    print(f"Relocatable bytes: {reloc_count}")

    # Convert bits to bytes (MSB first per byte)
    bitmap_bytes = bytearray()
    for i in range(0, len(bitmap_bits), 8):
        byte = 0
        for j in range(8):
            if i + j < len(bitmap_bits) and bitmap_bits[i + j]:
                byte |= (0x80 >> j)
        bitmap_bytes.append(byte)

    # Build SPR file
    spr_path = os.path.join(OUTDIR, 'SNIOS.SPR')
    spr = build_spr(code_0000, bitmap_bytes, spr_path)

    combined_sectors = math.ceil((code_len + len(bitmap_bytes)) / 128)

    print(f"SPR file: {spr_path}")
    print(f"  Parameter + data: 256 bytes")
    print(f"  Code+bitmap: {combined_sectors} sectors ({combined_sectors * 128} bytes)")
    print(f"    (code {code_len}B + bitmap {len(bitmap_bytes)}B packed together)")
    print(f"  Total: {len(spr)} bytes")

    # Verify: simulate loading at a test address
    test_addr = 0xD800
    test_bias = test_addr >> 8
    relocated = bytearray(code_0000)
    for i in range(code_len):
        if bitmap_bits[i]:
            relocated[i] = (relocated[i] + test_bias) & 0xFF
    print(f"\nVerification: simulated load at {test_addr:04X}h")
    print(f"  NTWKIN JP target: {relocated[1]:02X}{relocated[2]:02X}h → "
          f"{test_addr + code_0000[1] + (code_0000[2] << 8):04X}h")

    return 0


if __name__ == '__main__':
    sys.exit(main())
