#!/usr/bin/env python3
"""Generate sumtest.asm as a fully unrolled sum(1..N).

Full unroll makes the ASM source large (≈3 KB for N=100), so every
CP/NET READ-SEQ on the slave pulls many 128-byte records from the
master's disk.  If any record comes back corrupt (dropped byte,
duplicated sector, wrong LBA, …), the assembler emits a wrong
HEX record, LOAD turns that into a wrong COM byte, and the running
program prints something other than the expected "CPNET OK XXXX".
That is the pass/fail signal we want -- no byte-exact check on the
COM image itself, only on what the program computes and emits.
"""
import os

N = 1000                        # sum(1..N); adjust to change target
# Sum exceeds 16 bits for N >= 362.  HL wraps mod 2^16 via DAD, which
# is what we check against.  For N=1000, sum = 500500, HL = 500500 &
# 0xFFFF = 0xA314.
EXPECTED = sum(range(1, N + 1)) & 0xFFFF

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'sumtest.asm')

preamble = f"""; sumtest.asm -- CP/NOS end-to-end smoke test (GENERATED; do not hand-edit).
;
; Generated by mksmokeasm.py with N = {N}, expected HL = 0x{EXPECTED:04X}.
;
; Pure 8080, meant to be assembled ON the slave by CP/M ASM.COM
; (served from master drive B: = cpm22-1.dsk).  The smoke test drives
; this across the CP/NET wire:
;
;   B:ASM D:SUMTEST.DDZ    (assemble; read SRC, write HEX, no listing)
;   B:LOAD D:SUMTEST       (HEX -> COM)
;   D:SUMTEST              (execute; prints "CPNET OK {EXPECTED:04X}")
;
; The sum-of-1..N accumulation is fully unrolled -- N pairs of
; (LXI D,n ; DAD D) -- so the source is deliberately ~{5 + N*3} lines,
; forcing dozens of CP/NET READ-SEQ round-trips during assembly.

BDOS    equ     0005h
CONOUT  equ     2
PRINTS  equ     9

        aseg                    ; absolute (CP/M .COM) not relocatable
        org     0100h

start:  ; entry point referenced by END
        ; HL = sum(1..{N}), fully unrolled.
        lxi     h, 0
"""

body_lines = []
for i in range(1, N + 1):
    body_lines.append(f"        lxi     d, {i}")
    body_lines.append(f"        dad     d")

postamble = """
        ; Print leading message.  BDOS trashes HL, so preserve sum.
        push    h
        lxi     d, msg1
        mvi     c, PRINTS
        call    BDOS
        pop     h

        ; Print HL as 4 hex digits.
        mov     a, h
        rrc
        rrc
        rrc
        rrc
        call    pnib
        mov     a, h
        call    pnib
        mov     a, l
        rrc
        rrc
        rrc
        rrc
        call    pnib
        mov     a, l
        call    pnib

        ; Print trailing CR/LF.
        lxi     d, msg2
        mvi     c, PRINTS
        call    BDOS

        ; Signal "test complete" via I/O port write.  MAME Lua taps
        ; install_write_tap on this port to time the workload without
        ; needing to scrape SIO-B for "CPNET OK".  Port 80h is in the
        ; unmapped 0x20-0xEF range on the RC702 (the only mapped IO
        ; ranges are 0x00-0x1F and 0xF0-0xFF — see rc702.cpp:167-175);
        ; harness side picks up the OUT atomically.  A is "U" (0x55)
        ; for "Unique done"; any value would work — only the write
        ; event matters.
        mvi     a, 055h
        out     080h

        ; CP/M warm-boot via zero-page (= JP NDOS WBOOT wrapper, which
        ; reloads CCP and prompts again).  Plain RET would also work
        ; since sumtest's small TPA footprint leaves CCP intact, but
        ; jmp 0 is the canonical CP/M idiom for transient programs.
        jmp     0

pnib:
        ani     0fh
        adi     '0'
        cpi     '9'+1
        jc      pok
        adi     7               ; 'A' - '9' - 1 = 7
pok:
        push    h
        push    b
        mov     e, a
        mvi     c, CONOUT
        call    BDOS
        pop     b
        pop     h
        ret

msg1:   db      'CPNET OK $'
msg2:   db      0dh, 0ah, '$'

        END
"""

with open(OUT, 'w', newline='\r\n') as f:
    f.write(preamble)
    f.write("\n".join(body_lines) + "\n")
    f.write(postamble)

print(f"wrote {OUT} ({os.path.getsize(OUT)} bytes)")
print(f"expected output: 'CPNET OK {EXPECTED:04X}'")
