; sumtest.asm -- CP/NOS end-to-end smoke test (GENERATED; do not hand-edit).
;
; Generated by mksmokeasm.py with N = 1000, expected HL = 0xA314.
;
; Pure 8080, meant to be assembled ON the slave by CP/M ASM.COM
; (served from master drive B: = cpm22-1.dsk).  The smoke test drives
; this across the CP/NET wire:
;
;   B:ASM D:SUMTEST.DDZ    (assemble; read SRC, write HEX, no listing)
;   B:LOAD D:SUMTEST       (HEX -> COM)
;   D:SUMTEST              (execute; prints "CPNET OK A314")
;
; The sum-of-1..N accumulation is fully unrolled -- N pairs of
; (LXI D,n ; DAD D) -- so the source is deliberately ~3005 lines,
; forcing dozens of CP/NET READ-SEQ round-trips during assembly.

BDOS    equ     0005h
CONOUT  equ     2
PRINTS  equ     9

        org     0100h

start:  ; entry point referenced by END
        ; HL = sum(1..1000), fully unrolled.
        lxi     h, 0
        lxi     d, 1
        dad     d
        lxi     d, 2
        dad     d
        lxi     d, 3
        dad     d
        lxi     d, 4
        dad     d
        lxi     d, 5
        dad     d
        lxi     d, 6
        dad     d
        lxi     d, 7
        dad     d
        lxi     d, 8
        dad     d
        lxi     d, 9
        dad     d
        lxi     d, 10
        dad     d
        lxi     d, 11
        dad     d
        lxi     d, 12
        dad     d
        lxi     d, 13
        dad     d
        lxi     d, 14
        dad     d
        lxi     d, 15
        dad     d
        lxi     d, 16
        dad     d
        lxi     d, 17
        dad     d
        lxi     d, 18
        dad     d
        lxi     d, 19
        dad     d
        lxi     d, 20
        dad     d
        lxi     d, 21
        dad     d
        lxi     d, 22
        dad     d
        lxi     d, 23
        dad     d
        lxi     d, 24
        dad     d
        lxi     d, 25
        dad     d
        lxi     d, 26
        dad     d
        lxi     d, 27
        dad     d
        lxi     d, 28
        dad     d
        lxi     d, 29
        dad     d
        lxi     d, 30
        dad     d
        lxi     d, 31
        dad     d
        lxi     d, 32
        dad     d
        lxi     d, 33
        dad     d
        lxi     d, 34
        dad     d
        lxi     d, 35
        dad     d
        lxi     d, 36
        dad     d
        lxi     d, 37
        dad     d
        lxi     d, 38
        dad     d
        lxi     d, 39
        dad     d
        lxi     d, 40
        dad     d
        lxi     d, 41
        dad     d
        lxi     d, 42
        dad     d
        lxi     d, 43
        dad     d
        lxi     d, 44
        dad     d
        lxi     d, 45
        dad     d
        lxi     d, 46
        dad     d
        lxi     d, 47
        dad     d
        lxi     d, 48
        dad     d
        lxi     d, 49
        dad     d
        lxi     d, 50
        dad     d
        lxi     d, 51
        dad     d
        lxi     d, 52
        dad     d
        lxi     d, 53
        dad     d
        lxi     d, 54
        dad     d
        lxi     d, 55
        dad     d
        lxi     d, 56
        dad     d
        lxi     d, 57
        dad     d
        lxi     d, 58
        dad     d
        lxi     d, 59
        dad     d
        lxi     d, 60
        dad     d
        lxi     d, 61
        dad     d
        lxi     d, 62
        dad     d
        lxi     d, 63
        dad     d
        lxi     d, 64
        dad     d
        lxi     d, 65
        dad     d
        lxi     d, 66
        dad     d
        lxi     d, 67
        dad     d
        lxi     d, 68
        dad     d
        lxi     d, 69
        dad     d
        lxi     d, 70
        dad     d
        lxi     d, 71
        dad     d
        lxi     d, 72
        dad     d
        lxi     d, 73
        dad     d
        lxi     d, 74
        dad     d
        lxi     d, 75
        dad     d
        lxi     d, 76
        dad     d
        lxi     d, 77
        dad     d
        lxi     d, 78
        dad     d
        lxi     d, 79
        dad     d
        lxi     d, 80
        dad     d
        lxi     d, 81
        dad     d
        lxi     d, 82
        dad     d
        lxi     d, 83
        dad     d
        lxi     d, 84
        dad     d
        lxi     d, 85
        dad     d
        lxi     d, 86
        dad     d
        lxi     d, 87
        dad     d
        lxi     d, 88
        dad     d
        lxi     d, 89
        dad     d
        lxi     d, 90
        dad     d
        lxi     d, 91
        dad     d
        lxi     d, 92
        dad     d
        lxi     d, 93
        dad     d
        lxi     d, 94
        dad     d
        lxi     d, 95
        dad     d
        lxi     d, 96
        dad     d
        lxi     d, 97
        dad     d
        lxi     d, 98
        dad     d
        lxi     d, 99
        dad     d
        lxi     d, 100
        dad     d
        lxi     d, 101
        dad     d
        lxi     d, 102
        dad     d
        lxi     d, 103
        dad     d
        lxi     d, 104
        dad     d
        lxi     d, 105
        dad     d
        lxi     d, 106
        dad     d
        lxi     d, 107
        dad     d
        lxi     d, 108
        dad     d
        lxi     d, 109
        dad     d
        lxi     d, 110
        dad     d
        lxi     d, 111
        dad     d
        lxi     d, 112
        dad     d
        lxi     d, 113
        dad     d
        lxi     d, 114
        dad     d
        lxi     d, 115
        dad     d
        lxi     d, 116
        dad     d
        lxi     d, 117
        dad     d
        lxi     d, 118
        dad     d
        lxi     d, 119
        dad     d
        lxi     d, 120
        dad     d
        lxi     d, 121
        dad     d
        lxi     d, 122
        dad     d
        lxi     d, 123
        dad     d
        lxi     d, 124
        dad     d
        lxi     d, 125
        dad     d
        lxi     d, 126
        dad     d
        lxi     d, 127
        dad     d
        lxi     d, 128
        dad     d
        lxi     d, 129
        dad     d
        lxi     d, 130
        dad     d
        lxi     d, 131
        dad     d
        lxi     d, 132
        dad     d
        lxi     d, 133
        dad     d
        lxi     d, 134
        dad     d
        lxi     d, 135
        dad     d
        lxi     d, 136
        dad     d
        lxi     d, 137
        dad     d
        lxi     d, 138
        dad     d
        lxi     d, 139
        dad     d
        lxi     d, 140
        dad     d
        lxi     d, 141
        dad     d
        lxi     d, 142
        dad     d
        lxi     d, 143
        dad     d
        lxi     d, 144
        dad     d
        lxi     d, 145
        dad     d
        lxi     d, 146
        dad     d
        lxi     d, 147
        dad     d
        lxi     d, 148
        dad     d
        lxi     d, 149
        dad     d
        lxi     d, 150
        dad     d
        lxi     d, 151
        dad     d
        lxi     d, 152
        dad     d
        lxi     d, 153
        dad     d
        lxi     d, 154
        dad     d
        lxi     d, 155
        dad     d
        lxi     d, 156
        dad     d
        lxi     d, 157
        dad     d
        lxi     d, 158
        dad     d
        lxi     d, 159
        dad     d
        lxi     d, 160
        dad     d
        lxi     d, 161
        dad     d
        lxi     d, 162
        dad     d
        lxi     d, 163
        dad     d
        lxi     d, 164
        dad     d
        lxi     d, 165
        dad     d
        lxi     d, 166
        dad     d
        lxi     d, 167
        dad     d
        lxi     d, 168
        dad     d
        lxi     d, 169
        dad     d
        lxi     d, 170
        dad     d
        lxi     d, 171
        dad     d
        lxi     d, 172
        dad     d
        lxi     d, 173
        dad     d
        lxi     d, 174
        dad     d
        lxi     d, 175
        dad     d
        lxi     d, 176
        dad     d
        lxi     d, 177
        dad     d
        lxi     d, 178
        dad     d
        lxi     d, 179
        dad     d
        lxi     d, 180
        dad     d
        lxi     d, 181
        dad     d
        lxi     d, 182
        dad     d
        lxi     d, 183
        dad     d
        lxi     d, 184
        dad     d
        lxi     d, 185
        dad     d
        lxi     d, 186
        dad     d
        lxi     d, 187
        dad     d
        lxi     d, 188
        dad     d
        lxi     d, 189
        dad     d
        lxi     d, 190
        dad     d
        lxi     d, 191
        dad     d
        lxi     d, 192
        dad     d
        lxi     d, 193
        dad     d
        lxi     d, 194
        dad     d
        lxi     d, 195
        dad     d
        lxi     d, 196
        dad     d
        lxi     d, 197
        dad     d
        lxi     d, 198
        dad     d
        lxi     d, 199
        dad     d
        lxi     d, 200
        dad     d
        lxi     d, 201
        dad     d
        lxi     d, 202
        dad     d
        lxi     d, 203
        dad     d
        lxi     d, 204
        dad     d
        lxi     d, 205
        dad     d
        lxi     d, 206
        dad     d
        lxi     d, 207
        dad     d
        lxi     d, 208
        dad     d
        lxi     d, 209
        dad     d
        lxi     d, 210
        dad     d
        lxi     d, 211
        dad     d
        lxi     d, 212
        dad     d
        lxi     d, 213
        dad     d
        lxi     d, 214
        dad     d
        lxi     d, 215
        dad     d
        lxi     d, 216
        dad     d
        lxi     d, 217
        dad     d
        lxi     d, 218
        dad     d
        lxi     d, 219
        dad     d
        lxi     d, 220
        dad     d
        lxi     d, 221
        dad     d
        lxi     d, 222
        dad     d
        lxi     d, 223
        dad     d
        lxi     d, 224
        dad     d
        lxi     d, 225
        dad     d
        lxi     d, 226
        dad     d
        lxi     d, 227
        dad     d
        lxi     d, 228
        dad     d
        lxi     d, 229
        dad     d
        lxi     d, 230
        dad     d
        lxi     d, 231
        dad     d
        lxi     d, 232
        dad     d
        lxi     d, 233
        dad     d
        lxi     d, 234
        dad     d
        lxi     d, 235
        dad     d
        lxi     d, 236
        dad     d
        lxi     d, 237
        dad     d
        lxi     d, 238
        dad     d
        lxi     d, 239
        dad     d
        lxi     d, 240
        dad     d
        lxi     d, 241
        dad     d
        lxi     d, 242
        dad     d
        lxi     d, 243
        dad     d
        lxi     d, 244
        dad     d
        lxi     d, 245
        dad     d
        lxi     d, 246
        dad     d
        lxi     d, 247
        dad     d
        lxi     d, 248
        dad     d
        lxi     d, 249
        dad     d
        lxi     d, 250
        dad     d
        lxi     d, 251
        dad     d
        lxi     d, 252
        dad     d
        lxi     d, 253
        dad     d
        lxi     d, 254
        dad     d
        lxi     d, 255
        dad     d
        lxi     d, 256
        dad     d
        lxi     d, 257
        dad     d
        lxi     d, 258
        dad     d
        lxi     d, 259
        dad     d
        lxi     d, 260
        dad     d
        lxi     d, 261
        dad     d
        lxi     d, 262
        dad     d
        lxi     d, 263
        dad     d
        lxi     d, 264
        dad     d
        lxi     d, 265
        dad     d
        lxi     d, 266
        dad     d
        lxi     d, 267
        dad     d
        lxi     d, 268
        dad     d
        lxi     d, 269
        dad     d
        lxi     d, 270
        dad     d
        lxi     d, 271
        dad     d
        lxi     d, 272
        dad     d
        lxi     d, 273
        dad     d
        lxi     d, 274
        dad     d
        lxi     d, 275
        dad     d
        lxi     d, 276
        dad     d
        lxi     d, 277
        dad     d
        lxi     d, 278
        dad     d
        lxi     d, 279
        dad     d
        lxi     d, 280
        dad     d
        lxi     d, 281
        dad     d
        lxi     d, 282
        dad     d
        lxi     d, 283
        dad     d
        lxi     d, 284
        dad     d
        lxi     d, 285
        dad     d
        lxi     d, 286
        dad     d
        lxi     d, 287
        dad     d
        lxi     d, 288
        dad     d
        lxi     d, 289
        dad     d
        lxi     d, 290
        dad     d
        lxi     d, 291
        dad     d
        lxi     d, 292
        dad     d
        lxi     d, 293
        dad     d
        lxi     d, 294
        dad     d
        lxi     d, 295
        dad     d
        lxi     d, 296
        dad     d
        lxi     d, 297
        dad     d
        lxi     d, 298
        dad     d
        lxi     d, 299
        dad     d
        lxi     d, 300
        dad     d
        lxi     d, 301
        dad     d
        lxi     d, 302
        dad     d
        lxi     d, 303
        dad     d
        lxi     d, 304
        dad     d
        lxi     d, 305
        dad     d
        lxi     d, 306
        dad     d
        lxi     d, 307
        dad     d
        lxi     d, 308
        dad     d
        lxi     d, 309
        dad     d
        lxi     d, 310
        dad     d
        lxi     d, 311
        dad     d
        lxi     d, 312
        dad     d
        lxi     d, 313
        dad     d
        lxi     d, 314
        dad     d
        lxi     d, 315
        dad     d
        lxi     d, 316
        dad     d
        lxi     d, 317
        dad     d
        lxi     d, 318
        dad     d
        lxi     d, 319
        dad     d
        lxi     d, 320
        dad     d
        lxi     d, 321
        dad     d
        lxi     d, 322
        dad     d
        lxi     d, 323
        dad     d
        lxi     d, 324
        dad     d
        lxi     d, 325
        dad     d
        lxi     d, 326
        dad     d
        lxi     d, 327
        dad     d
        lxi     d, 328
        dad     d
        lxi     d, 329
        dad     d
        lxi     d, 330
        dad     d
        lxi     d, 331
        dad     d
        lxi     d, 332
        dad     d
        lxi     d, 333
        dad     d
        lxi     d, 334
        dad     d
        lxi     d, 335
        dad     d
        lxi     d, 336
        dad     d
        lxi     d, 337
        dad     d
        lxi     d, 338
        dad     d
        lxi     d, 339
        dad     d
        lxi     d, 340
        dad     d
        lxi     d, 341
        dad     d
        lxi     d, 342
        dad     d
        lxi     d, 343
        dad     d
        lxi     d, 344
        dad     d
        lxi     d, 345
        dad     d
        lxi     d, 346
        dad     d
        lxi     d, 347
        dad     d
        lxi     d, 348
        dad     d
        lxi     d, 349
        dad     d
        lxi     d, 350
        dad     d
        lxi     d, 351
        dad     d
        lxi     d, 352
        dad     d
        lxi     d, 353
        dad     d
        lxi     d, 354
        dad     d
        lxi     d, 355
        dad     d
        lxi     d, 356
        dad     d
        lxi     d, 357
        dad     d
        lxi     d, 358
        dad     d
        lxi     d, 359
        dad     d
        lxi     d, 360
        dad     d
        lxi     d, 361
        dad     d
        lxi     d, 362
        dad     d
        lxi     d, 363
        dad     d
        lxi     d, 364
        dad     d
        lxi     d, 365
        dad     d
        lxi     d, 366
        dad     d
        lxi     d, 367
        dad     d
        lxi     d, 368
        dad     d
        lxi     d, 369
        dad     d
        lxi     d, 370
        dad     d
        lxi     d, 371
        dad     d
        lxi     d, 372
        dad     d
        lxi     d, 373
        dad     d
        lxi     d, 374
        dad     d
        lxi     d, 375
        dad     d
        lxi     d, 376
        dad     d
        lxi     d, 377
        dad     d
        lxi     d, 378
        dad     d
        lxi     d, 379
        dad     d
        lxi     d, 380
        dad     d
        lxi     d, 381
        dad     d
        lxi     d, 382
        dad     d
        lxi     d, 383
        dad     d
        lxi     d, 384
        dad     d
        lxi     d, 385
        dad     d
        lxi     d, 386
        dad     d
        lxi     d, 387
        dad     d
        lxi     d, 388
        dad     d
        lxi     d, 389
        dad     d
        lxi     d, 390
        dad     d
        lxi     d, 391
        dad     d
        lxi     d, 392
        dad     d
        lxi     d, 393
        dad     d
        lxi     d, 394
        dad     d
        lxi     d, 395
        dad     d
        lxi     d, 396
        dad     d
        lxi     d, 397
        dad     d
        lxi     d, 398
        dad     d
        lxi     d, 399
        dad     d
        lxi     d, 400
        dad     d
        lxi     d, 401
        dad     d
        lxi     d, 402
        dad     d
        lxi     d, 403
        dad     d
        lxi     d, 404
        dad     d
        lxi     d, 405
        dad     d
        lxi     d, 406
        dad     d
        lxi     d, 407
        dad     d
        lxi     d, 408
        dad     d
        lxi     d, 409
        dad     d
        lxi     d, 410
        dad     d
        lxi     d, 411
        dad     d
        lxi     d, 412
        dad     d
        lxi     d, 413
        dad     d
        lxi     d, 414
        dad     d
        lxi     d, 415
        dad     d
        lxi     d, 416
        dad     d
        lxi     d, 417
        dad     d
        lxi     d, 418
        dad     d
        lxi     d, 419
        dad     d
        lxi     d, 420
        dad     d
        lxi     d, 421
        dad     d
        lxi     d, 422
        dad     d
        lxi     d, 423
        dad     d
        lxi     d, 424
        dad     d
        lxi     d, 425
        dad     d
        lxi     d, 426
        dad     d
        lxi     d, 427
        dad     d
        lxi     d, 428
        dad     d
        lxi     d, 429
        dad     d
        lxi     d, 430
        dad     d
        lxi     d, 431
        dad     d
        lxi     d, 432
        dad     d
        lxi     d, 433
        dad     d
        lxi     d, 434
        dad     d
        lxi     d, 435
        dad     d
        lxi     d, 436
        dad     d
        lxi     d, 437
        dad     d
        lxi     d, 438
        dad     d
        lxi     d, 439
        dad     d
        lxi     d, 440
        dad     d
        lxi     d, 441
        dad     d
        lxi     d, 442
        dad     d
        lxi     d, 443
        dad     d
        lxi     d, 444
        dad     d
        lxi     d, 445
        dad     d
        lxi     d, 446
        dad     d
        lxi     d, 447
        dad     d
        lxi     d, 448
        dad     d
        lxi     d, 449
        dad     d
        lxi     d, 450
        dad     d
        lxi     d, 451
        dad     d
        lxi     d, 452
        dad     d
        lxi     d, 453
        dad     d
        lxi     d, 454
        dad     d
        lxi     d, 455
        dad     d
        lxi     d, 456
        dad     d
        lxi     d, 457
        dad     d
        lxi     d, 458
        dad     d
        lxi     d, 459
        dad     d
        lxi     d, 460
        dad     d
        lxi     d, 461
        dad     d
        lxi     d, 462
        dad     d
        lxi     d, 463
        dad     d
        lxi     d, 464
        dad     d
        lxi     d, 465
        dad     d
        lxi     d, 466
        dad     d
        lxi     d, 467
        dad     d
        lxi     d, 468
        dad     d
        lxi     d, 469
        dad     d
        lxi     d, 470
        dad     d
        lxi     d, 471
        dad     d
        lxi     d, 472
        dad     d
        lxi     d, 473
        dad     d
        lxi     d, 474
        dad     d
        lxi     d, 475
        dad     d
        lxi     d, 476
        dad     d
        lxi     d, 477
        dad     d
        lxi     d, 478
        dad     d
        lxi     d, 479
        dad     d
        lxi     d, 480
        dad     d
        lxi     d, 481
        dad     d
        lxi     d, 482
        dad     d
        lxi     d, 483
        dad     d
        lxi     d, 484
        dad     d
        lxi     d, 485
        dad     d
        lxi     d, 486
        dad     d
        lxi     d, 487
        dad     d
        lxi     d, 488
        dad     d
        lxi     d, 489
        dad     d
        lxi     d, 490
        dad     d
        lxi     d, 491
        dad     d
        lxi     d, 492
        dad     d
        lxi     d, 493
        dad     d
        lxi     d, 494
        dad     d
        lxi     d, 495
        dad     d
        lxi     d, 496
        dad     d
        lxi     d, 497
        dad     d
        lxi     d, 498
        dad     d
        lxi     d, 499
        dad     d
        lxi     d, 500
        dad     d
        lxi     d, 501
        dad     d
        lxi     d, 502
        dad     d
        lxi     d, 503
        dad     d
        lxi     d, 504
        dad     d
        lxi     d, 505
        dad     d
        lxi     d, 506
        dad     d
        lxi     d, 507
        dad     d
        lxi     d, 508
        dad     d
        lxi     d, 509
        dad     d
        lxi     d, 510
        dad     d
        lxi     d, 511
        dad     d
        lxi     d, 512
        dad     d
        lxi     d, 513
        dad     d
        lxi     d, 514
        dad     d
        lxi     d, 515
        dad     d
        lxi     d, 516
        dad     d
        lxi     d, 517
        dad     d
        lxi     d, 518
        dad     d
        lxi     d, 519
        dad     d
        lxi     d, 520
        dad     d
        lxi     d, 521
        dad     d
        lxi     d, 522
        dad     d
        lxi     d, 523
        dad     d
        lxi     d, 524
        dad     d
        lxi     d, 525
        dad     d
        lxi     d, 526
        dad     d
        lxi     d, 527
        dad     d
        lxi     d, 528
        dad     d
        lxi     d, 529
        dad     d
        lxi     d, 530
        dad     d
        lxi     d, 531
        dad     d
        lxi     d, 532
        dad     d
        lxi     d, 533
        dad     d
        lxi     d, 534
        dad     d
        lxi     d, 535
        dad     d
        lxi     d, 536
        dad     d
        lxi     d, 537
        dad     d
        lxi     d, 538
        dad     d
        lxi     d, 539
        dad     d
        lxi     d, 540
        dad     d
        lxi     d, 541
        dad     d
        lxi     d, 542
        dad     d
        lxi     d, 543
        dad     d
        lxi     d, 544
        dad     d
        lxi     d, 545
        dad     d
        lxi     d, 546
        dad     d
        lxi     d, 547
        dad     d
        lxi     d, 548
        dad     d
        lxi     d, 549
        dad     d
        lxi     d, 550
        dad     d
        lxi     d, 551
        dad     d
        lxi     d, 552
        dad     d
        lxi     d, 553
        dad     d
        lxi     d, 554
        dad     d
        lxi     d, 555
        dad     d
        lxi     d, 556
        dad     d
        lxi     d, 557
        dad     d
        lxi     d, 558
        dad     d
        lxi     d, 559
        dad     d
        lxi     d, 560
        dad     d
        lxi     d, 561
        dad     d
        lxi     d, 562
        dad     d
        lxi     d, 563
        dad     d
        lxi     d, 564
        dad     d
        lxi     d, 565
        dad     d
        lxi     d, 566
        dad     d
        lxi     d, 567
        dad     d
        lxi     d, 568
        dad     d
        lxi     d, 569
        dad     d
        lxi     d, 570
        dad     d
        lxi     d, 571
        dad     d
        lxi     d, 572
        dad     d
        lxi     d, 573
        dad     d
        lxi     d, 574
        dad     d
        lxi     d, 575
        dad     d
        lxi     d, 576
        dad     d
        lxi     d, 577
        dad     d
        lxi     d, 578
        dad     d
        lxi     d, 579
        dad     d
        lxi     d, 580
        dad     d
        lxi     d, 581
        dad     d
        lxi     d, 582
        dad     d
        lxi     d, 583
        dad     d
        lxi     d, 584
        dad     d
        lxi     d, 585
        dad     d
        lxi     d, 586
        dad     d
        lxi     d, 587
        dad     d
        lxi     d, 588
        dad     d
        lxi     d, 589
        dad     d
        lxi     d, 590
        dad     d
        lxi     d, 591
        dad     d
        lxi     d, 592
        dad     d
        lxi     d, 593
        dad     d
        lxi     d, 594
        dad     d
        lxi     d, 595
        dad     d
        lxi     d, 596
        dad     d
        lxi     d, 597
        dad     d
        lxi     d, 598
        dad     d
        lxi     d, 599
        dad     d
        lxi     d, 600
        dad     d
        lxi     d, 601
        dad     d
        lxi     d, 602
        dad     d
        lxi     d, 603
        dad     d
        lxi     d, 604
        dad     d
        lxi     d, 605
        dad     d
        lxi     d, 606
        dad     d
        lxi     d, 607
        dad     d
        lxi     d, 608
        dad     d
        lxi     d, 609
        dad     d
        lxi     d, 610
        dad     d
        lxi     d, 611
        dad     d
        lxi     d, 612
        dad     d
        lxi     d, 613
        dad     d
        lxi     d, 614
        dad     d
        lxi     d, 615
        dad     d
        lxi     d, 616
        dad     d
        lxi     d, 617
        dad     d
        lxi     d, 618
        dad     d
        lxi     d, 619
        dad     d
        lxi     d, 620
        dad     d
        lxi     d, 621
        dad     d
        lxi     d, 622
        dad     d
        lxi     d, 623
        dad     d
        lxi     d, 624
        dad     d
        lxi     d, 625
        dad     d
        lxi     d, 626
        dad     d
        lxi     d, 627
        dad     d
        lxi     d, 628
        dad     d
        lxi     d, 629
        dad     d
        lxi     d, 630
        dad     d
        lxi     d, 631
        dad     d
        lxi     d, 632
        dad     d
        lxi     d, 633
        dad     d
        lxi     d, 634
        dad     d
        lxi     d, 635
        dad     d
        lxi     d, 636
        dad     d
        lxi     d, 637
        dad     d
        lxi     d, 638
        dad     d
        lxi     d, 639
        dad     d
        lxi     d, 640
        dad     d
        lxi     d, 641
        dad     d
        lxi     d, 642
        dad     d
        lxi     d, 643
        dad     d
        lxi     d, 644
        dad     d
        lxi     d, 645
        dad     d
        lxi     d, 646
        dad     d
        lxi     d, 647
        dad     d
        lxi     d, 648
        dad     d
        lxi     d, 649
        dad     d
        lxi     d, 650
        dad     d
        lxi     d, 651
        dad     d
        lxi     d, 652
        dad     d
        lxi     d, 653
        dad     d
        lxi     d, 654
        dad     d
        lxi     d, 655
        dad     d
        lxi     d, 656
        dad     d
        lxi     d, 657
        dad     d
        lxi     d, 658
        dad     d
        lxi     d, 659
        dad     d
        lxi     d, 660
        dad     d
        lxi     d, 661
        dad     d
        lxi     d, 662
        dad     d
        lxi     d, 663
        dad     d
        lxi     d, 664
        dad     d
        lxi     d, 665
        dad     d
        lxi     d, 666
        dad     d
        lxi     d, 667
        dad     d
        lxi     d, 668
        dad     d
        lxi     d, 669
        dad     d
        lxi     d, 670
        dad     d
        lxi     d, 671
        dad     d
        lxi     d, 672
        dad     d
        lxi     d, 673
        dad     d
        lxi     d, 674
        dad     d
        lxi     d, 675
        dad     d
        lxi     d, 676
        dad     d
        lxi     d, 677
        dad     d
        lxi     d, 678
        dad     d
        lxi     d, 679
        dad     d
        lxi     d, 680
        dad     d
        lxi     d, 681
        dad     d
        lxi     d, 682
        dad     d
        lxi     d, 683
        dad     d
        lxi     d, 684
        dad     d
        lxi     d, 685
        dad     d
        lxi     d, 686
        dad     d
        lxi     d, 687
        dad     d
        lxi     d, 688
        dad     d
        lxi     d, 689
        dad     d
        lxi     d, 690
        dad     d
        lxi     d, 691
        dad     d
        lxi     d, 692
        dad     d
        lxi     d, 693
        dad     d
        lxi     d, 694
        dad     d
        lxi     d, 695
        dad     d
        lxi     d, 696
        dad     d
        lxi     d, 697
        dad     d
        lxi     d, 698
        dad     d
        lxi     d, 699
        dad     d
        lxi     d, 700
        dad     d
        lxi     d, 701
        dad     d
        lxi     d, 702
        dad     d
        lxi     d, 703
        dad     d
        lxi     d, 704
        dad     d
        lxi     d, 705
        dad     d
        lxi     d, 706
        dad     d
        lxi     d, 707
        dad     d
        lxi     d, 708
        dad     d
        lxi     d, 709
        dad     d
        lxi     d, 710
        dad     d
        lxi     d, 711
        dad     d
        lxi     d, 712
        dad     d
        lxi     d, 713
        dad     d
        lxi     d, 714
        dad     d
        lxi     d, 715
        dad     d
        lxi     d, 716
        dad     d
        lxi     d, 717
        dad     d
        lxi     d, 718
        dad     d
        lxi     d, 719
        dad     d
        lxi     d, 720
        dad     d
        lxi     d, 721
        dad     d
        lxi     d, 722
        dad     d
        lxi     d, 723
        dad     d
        lxi     d, 724
        dad     d
        lxi     d, 725
        dad     d
        lxi     d, 726
        dad     d
        lxi     d, 727
        dad     d
        lxi     d, 728
        dad     d
        lxi     d, 729
        dad     d
        lxi     d, 730
        dad     d
        lxi     d, 731
        dad     d
        lxi     d, 732
        dad     d
        lxi     d, 733
        dad     d
        lxi     d, 734
        dad     d
        lxi     d, 735
        dad     d
        lxi     d, 736
        dad     d
        lxi     d, 737
        dad     d
        lxi     d, 738
        dad     d
        lxi     d, 739
        dad     d
        lxi     d, 740
        dad     d
        lxi     d, 741
        dad     d
        lxi     d, 742
        dad     d
        lxi     d, 743
        dad     d
        lxi     d, 744
        dad     d
        lxi     d, 745
        dad     d
        lxi     d, 746
        dad     d
        lxi     d, 747
        dad     d
        lxi     d, 748
        dad     d
        lxi     d, 749
        dad     d
        lxi     d, 750
        dad     d
        lxi     d, 751
        dad     d
        lxi     d, 752
        dad     d
        lxi     d, 753
        dad     d
        lxi     d, 754
        dad     d
        lxi     d, 755
        dad     d
        lxi     d, 756
        dad     d
        lxi     d, 757
        dad     d
        lxi     d, 758
        dad     d
        lxi     d, 759
        dad     d
        lxi     d, 760
        dad     d
        lxi     d, 761
        dad     d
        lxi     d, 762
        dad     d
        lxi     d, 763
        dad     d
        lxi     d, 764
        dad     d
        lxi     d, 765
        dad     d
        lxi     d, 766
        dad     d
        lxi     d, 767
        dad     d
        lxi     d, 768
        dad     d
        lxi     d, 769
        dad     d
        lxi     d, 770
        dad     d
        lxi     d, 771
        dad     d
        lxi     d, 772
        dad     d
        lxi     d, 773
        dad     d
        lxi     d, 774
        dad     d
        lxi     d, 775
        dad     d
        lxi     d, 776
        dad     d
        lxi     d, 777
        dad     d
        lxi     d, 778
        dad     d
        lxi     d, 779
        dad     d
        lxi     d, 780
        dad     d
        lxi     d, 781
        dad     d
        lxi     d, 782
        dad     d
        lxi     d, 783
        dad     d
        lxi     d, 784
        dad     d
        lxi     d, 785
        dad     d
        lxi     d, 786
        dad     d
        lxi     d, 787
        dad     d
        lxi     d, 788
        dad     d
        lxi     d, 789
        dad     d
        lxi     d, 790
        dad     d
        lxi     d, 791
        dad     d
        lxi     d, 792
        dad     d
        lxi     d, 793
        dad     d
        lxi     d, 794
        dad     d
        lxi     d, 795
        dad     d
        lxi     d, 796
        dad     d
        lxi     d, 797
        dad     d
        lxi     d, 798
        dad     d
        lxi     d, 799
        dad     d
        lxi     d, 800
        dad     d
        lxi     d, 801
        dad     d
        lxi     d, 802
        dad     d
        lxi     d, 803
        dad     d
        lxi     d, 804
        dad     d
        lxi     d, 805
        dad     d
        lxi     d, 806
        dad     d
        lxi     d, 807
        dad     d
        lxi     d, 808
        dad     d
        lxi     d, 809
        dad     d
        lxi     d, 810
        dad     d
        lxi     d, 811
        dad     d
        lxi     d, 812
        dad     d
        lxi     d, 813
        dad     d
        lxi     d, 814
        dad     d
        lxi     d, 815
        dad     d
        lxi     d, 816
        dad     d
        lxi     d, 817
        dad     d
        lxi     d, 818
        dad     d
        lxi     d, 819
        dad     d
        lxi     d, 820
        dad     d
        lxi     d, 821
        dad     d
        lxi     d, 822
        dad     d
        lxi     d, 823
        dad     d
        lxi     d, 824
        dad     d
        lxi     d, 825
        dad     d
        lxi     d, 826
        dad     d
        lxi     d, 827
        dad     d
        lxi     d, 828
        dad     d
        lxi     d, 829
        dad     d
        lxi     d, 830
        dad     d
        lxi     d, 831
        dad     d
        lxi     d, 832
        dad     d
        lxi     d, 833
        dad     d
        lxi     d, 834
        dad     d
        lxi     d, 835
        dad     d
        lxi     d, 836
        dad     d
        lxi     d, 837
        dad     d
        lxi     d, 838
        dad     d
        lxi     d, 839
        dad     d
        lxi     d, 840
        dad     d
        lxi     d, 841
        dad     d
        lxi     d, 842
        dad     d
        lxi     d, 843
        dad     d
        lxi     d, 844
        dad     d
        lxi     d, 845
        dad     d
        lxi     d, 846
        dad     d
        lxi     d, 847
        dad     d
        lxi     d, 848
        dad     d
        lxi     d, 849
        dad     d
        lxi     d, 850
        dad     d
        lxi     d, 851
        dad     d
        lxi     d, 852
        dad     d
        lxi     d, 853
        dad     d
        lxi     d, 854
        dad     d
        lxi     d, 855
        dad     d
        lxi     d, 856
        dad     d
        lxi     d, 857
        dad     d
        lxi     d, 858
        dad     d
        lxi     d, 859
        dad     d
        lxi     d, 860
        dad     d
        lxi     d, 861
        dad     d
        lxi     d, 862
        dad     d
        lxi     d, 863
        dad     d
        lxi     d, 864
        dad     d
        lxi     d, 865
        dad     d
        lxi     d, 866
        dad     d
        lxi     d, 867
        dad     d
        lxi     d, 868
        dad     d
        lxi     d, 869
        dad     d
        lxi     d, 870
        dad     d
        lxi     d, 871
        dad     d
        lxi     d, 872
        dad     d
        lxi     d, 873
        dad     d
        lxi     d, 874
        dad     d
        lxi     d, 875
        dad     d
        lxi     d, 876
        dad     d
        lxi     d, 877
        dad     d
        lxi     d, 878
        dad     d
        lxi     d, 879
        dad     d
        lxi     d, 880
        dad     d
        lxi     d, 881
        dad     d
        lxi     d, 882
        dad     d
        lxi     d, 883
        dad     d
        lxi     d, 884
        dad     d
        lxi     d, 885
        dad     d
        lxi     d, 886
        dad     d
        lxi     d, 887
        dad     d
        lxi     d, 888
        dad     d
        lxi     d, 889
        dad     d
        lxi     d, 890
        dad     d
        lxi     d, 891
        dad     d
        lxi     d, 892
        dad     d
        lxi     d, 893
        dad     d
        lxi     d, 894
        dad     d
        lxi     d, 895
        dad     d
        lxi     d, 896
        dad     d
        lxi     d, 897
        dad     d
        lxi     d, 898
        dad     d
        lxi     d, 899
        dad     d
        lxi     d, 900
        dad     d
        lxi     d, 901
        dad     d
        lxi     d, 902
        dad     d
        lxi     d, 903
        dad     d
        lxi     d, 904
        dad     d
        lxi     d, 905
        dad     d
        lxi     d, 906
        dad     d
        lxi     d, 907
        dad     d
        lxi     d, 908
        dad     d
        lxi     d, 909
        dad     d
        lxi     d, 910
        dad     d
        lxi     d, 911
        dad     d
        lxi     d, 912
        dad     d
        lxi     d, 913
        dad     d
        lxi     d, 914
        dad     d
        lxi     d, 915
        dad     d
        lxi     d, 916
        dad     d
        lxi     d, 917
        dad     d
        lxi     d, 918
        dad     d
        lxi     d, 919
        dad     d
        lxi     d, 920
        dad     d
        lxi     d, 921
        dad     d
        lxi     d, 922
        dad     d
        lxi     d, 923
        dad     d
        lxi     d, 924
        dad     d
        lxi     d, 925
        dad     d
        lxi     d, 926
        dad     d
        lxi     d, 927
        dad     d
        lxi     d, 928
        dad     d
        lxi     d, 929
        dad     d
        lxi     d, 930
        dad     d
        lxi     d, 931
        dad     d
        lxi     d, 932
        dad     d
        lxi     d, 933
        dad     d
        lxi     d, 934
        dad     d
        lxi     d, 935
        dad     d
        lxi     d, 936
        dad     d
        lxi     d, 937
        dad     d
        lxi     d, 938
        dad     d
        lxi     d, 939
        dad     d
        lxi     d, 940
        dad     d
        lxi     d, 941
        dad     d
        lxi     d, 942
        dad     d
        lxi     d, 943
        dad     d
        lxi     d, 944
        dad     d
        lxi     d, 945
        dad     d
        lxi     d, 946
        dad     d
        lxi     d, 947
        dad     d
        lxi     d, 948
        dad     d
        lxi     d, 949
        dad     d
        lxi     d, 950
        dad     d
        lxi     d, 951
        dad     d
        lxi     d, 952
        dad     d
        lxi     d, 953
        dad     d
        lxi     d, 954
        dad     d
        lxi     d, 955
        dad     d
        lxi     d, 956
        dad     d
        lxi     d, 957
        dad     d
        lxi     d, 958
        dad     d
        lxi     d, 959
        dad     d
        lxi     d, 960
        dad     d
        lxi     d, 961
        dad     d
        lxi     d, 962
        dad     d
        lxi     d, 963
        dad     d
        lxi     d, 964
        dad     d
        lxi     d, 965
        dad     d
        lxi     d, 966
        dad     d
        lxi     d, 967
        dad     d
        lxi     d, 968
        dad     d
        lxi     d, 969
        dad     d
        lxi     d, 970
        dad     d
        lxi     d, 971
        dad     d
        lxi     d, 972
        dad     d
        lxi     d, 973
        dad     d
        lxi     d, 974
        dad     d
        lxi     d, 975
        dad     d
        lxi     d, 976
        dad     d
        lxi     d, 977
        dad     d
        lxi     d, 978
        dad     d
        lxi     d, 979
        dad     d
        lxi     d, 980
        dad     d
        lxi     d, 981
        dad     d
        lxi     d, 982
        dad     d
        lxi     d, 983
        dad     d
        lxi     d, 984
        dad     d
        lxi     d, 985
        dad     d
        lxi     d, 986
        dad     d
        lxi     d, 987
        dad     d
        lxi     d, 988
        dad     d
        lxi     d, 989
        dad     d
        lxi     d, 990
        dad     d
        lxi     d, 991
        dad     d
        lxi     d, 992
        dad     d
        lxi     d, 993
        dad     d
        lxi     d, 994
        dad     d
        lxi     d, 995
        dad     d
        lxi     d, 996
        dad     d
        lxi     d, 997
        dad     d
        lxi     d, 998
        dad     d
        lxi     d, 999
        dad     d
        lxi     d, 1000
        dad     d

        ; Print leading message.
        lxi     d, msg1
        mvi     c, PRINTS
        call    BDOS

        ; Print HL as 4 hex digits.
        mov     a, h
        rrc
        rrc
        rrc
        rrc
        call    pnib
        mov     a, h
        call    pnib
        mov     a, l
        rrc
        rrc
        rrc
        rrc
        call    pnib
        mov     a, l
        call    pnib

        ; Print trailing CR/LF.
        lxi     d, msg2
        mvi     c, PRINTS
        call    BDOS

        ret                     ; warm-boot back to CCP

pnib:
        ani     0fh
        adi     '0'
        cpi     '9'+1
        jc      pok
        adi     7               ; 'A' - '9' - 1 = 7
pok:
        push    h
        push    b
        mov     e, a
        mvi     c, CONOUT
        call    BDOS
        pop     b
        pop     h
        ret

msg1:   db      'CPNET OK $'
msg2:   db      0dh, 0ah, '$'

        end     start
