; sumtest.asm -- CP/NOS end-to-end smoke test (GENERATED; do not hand-edit).
;
; Generated by mksmokeasm.py with N = 5, expected HL = 0x000F.
;
; Pure 8080, meant to be assembled ON the slave by CP/M ASM.COM
; (served from master drive B: = cpm22-1.dsk).  The smoke test drives
; this across the CP/NET wire:
;
;   B:ASM D:SUMTEST.DDZ    (assemble; read SRC, write HEX, no listing)
;   B:LOAD D:SUMTEST       (HEX -> COM)
;   D:SUMTEST              (execute; prints "CPNET OK 000F")
;
; The sum-of-1..N accumulation is fully unrolled -- N pairs of
; (LXI D,n ; DAD D) -- so the source is deliberately ~20 lines,
; forcing dozens of CP/NET READ-SEQ round-trips during assembly.

BDOS    equ     0005h
CONOUT  equ     2
PRINTS  equ     9

        org     0100h

start:  ; entry point referenced by END
        ; HL = sum(1..5), fully unrolled.
        lxi     h, 0
        lxi     d, 1
        dad     d
        lxi     d, 2
        dad     d
        lxi     d, 3
        dad     d
        lxi     d, 4
        dad     d
        lxi     d, 5
        dad     d

        ; Print leading message.
        lxi     d, msg1
        mvi     c, PRINTS
        call    BDOS

        ; Print HL as 4 hex digits.
        mov     a, h
        rrc
        rrc
        rrc
        rrc
        call    pnib
        mov     a, h
        call    pnib
        mov     a, l
        rrc
        rrc
        rrc
        rrc
        call    pnib
        mov     a, l
        call    pnib

        ; Print trailing CR/LF.
        lxi     d, msg2
        mvi     c, PRINTS
        call    BDOS

        ret                     ; warm-boot back to CCP

pnib:
        ani     0fh
        adi     '0'
        cpi     '9'+1
        jc      pok
        adi     7               ; 'A' - '9' - 1 = 7
pok:
        push    h
        push    b
        mov     e, a
        mvi     c, CONOUT
        call    BDOS
        pop     b
        pop     h
        ret

msg1:   db      'CPNET OK $'
msg2:   db      0dh, 0ah, '$'

        END
