/*
 * boot_entry.c — BOOT section: ROM entry point only.
 *
 * Compiled with --codeseg BOOT to place code at ORG 0x0000.
 * Only begin() lives here — it self-relocates the CODE payload
 * from ROM to RAM and jumps to init_relocated().
 */

#include <string.h>
#include <intrinsic.h>
#include "rom.h"

/* Linker symbols for self-relocation.
 * C adds _ prefix; linker sees __X for extern byte _X.
 * Taking &_X gives the linker-assigned address as a pointer. */
extern byte _BOOT_tail;    /* end of BOOT section = ROM source of CODE payload */
extern const byte intvec;  /* IVT at 0x7000: start of CODE payload */
extern const byte code_end;/* sentinel at end of CODE payload */

/* Post-relocation init (in init.c, relocated to RAM) */
extern void init_relocated(void);

/* ROM entry point — must be first function in BOOT section.
 * Copies CODE payload from ROM to RAM at 0x7000, then jumps there.
 * Note: &code_end - &intvec + 1 is computed at runtime (8 extra bytes
 * vs a linker-resolved constant).  No way found yet to make the linker
 * compute it without assembly code (DEFC). */
void begin(void)
{
    intrinsic_di();
    __asm__("ld sp, #" STR(ROM_STACK) "\n");
    memcpy((void *)&intvec, &_BOOT_tail, &code_end - &intvec + 1);
    init_relocated();
}

/* Build timestamp — in BOOT section, visible in ROM hex dump after begin().
 * Never called — just raw bytes in ROM.
 * BUILD_STAMP_STR is generated by the Makefile into build_stamp.h. */
#include "build_stamp.h"
void build_stamp(void) __naked { __asm__("DEFM " BUILD_STAMP_STR "\n"); }
