/*
 * boot_rom.c — BOOT section code.
 *
 * Lives in ROM at ORG 0x0000, accessible until prom_disable().
 * Contains:
 *   - Entry point: self-relocate CODE payload from ROM to RAM
 *   - banner_string    Raw banner text (referenced by display_banner in CODE)
 *   - NMI handler      RETN at 0x0066
 *   - init_fdc()       FDC Specify command (SDCC only; clang has it in rom.c)
 *
 * SDCC:  compiled with --codeseg BOOT, uses z80asm section directives.
 * clang: compiled without -ffunction-sections, uses GNU as directives.
 *        Linker script places all of boot.o .text at 0x0000 in ROM.
 *
 * IMPORTANT: Code in BOOT cannot call functions in CODE (memcpy, memset,
 * delay, etc.) — the CODE payload has not been copied to RAM yet when
 * BOOT runs.  Local boot_copy/boot_zero functions handle self-relocation.
 */

#ifdef __SDCC
#include <string.h>
#include <intrinsic.h>
#endif
#include "rom.h"

/* Post-relocation init (in rom.c, relocated to RAM) */
extern void init_relocated(void);

#if defined(__clang__) && !defined(HOST_TEST)
/* ================================================================
 * clang / llvm-z80
 * ================================================================ */

/* Linker symbols for self-relocation (defined in rc700_prom.ld).
 * C adds _ prefix: C `_code_load` → asm `__code_load`.
 * Declared as arrays so their "address" IS the linker-assigned value. */
extern char _code_load[], _code_start[], _code_size[];
extern char _bss_start[], _bss_size[];

/* ROM entry point at address 0x0000.  DI must be the very first
 * instruction at the Z80 reset vector — no C equivalent exists.
 * Sets SP and jumps to boot_main() for the C portion. */
__asm__(
    ".globl __start\n"
    "__start:\n"
    "\tdi\n"
    "\tld\tsp, " STR(ROM_STACK) "\n"
    "\tjp\t_boot_main\n"
);

/* Banner string — 42 bytes in BOOT section, referenced by
 * display_banner_and_start_crt() in CODE via extern.
 * CLANG_BANNER is generated by Makefile into clang_z80/banner.h. */
#include "clang_z80/banner.h"
__attribute__((section(".text"), used))
const char banner_string[42] = CLANG_BANNER;

/* NMI handler at Z80 hardwired vector 0x0066.
 * RETN restores IFF1 from IFF2 — no C equivalent. */
__asm__(
    ".org 0x0066\n"
    ".globl _nmi_handler\n"
    "_nmi_handler:\n"
    "\tretn\n"
);

/* Copy n bytes from src to dest.  Local to BOOT section — cannot call
 * memcpy() because it lives in CODE which hasn't been copied yet. */
static void boot_copy(char *dest, const char *src, unsigned n) {
    while (n--) {
        *dest++ = *src++;
    }
}

/* Zero n bytes at dest.  Local to BOOT — cannot call memset(). */
static void boot_zero(char *dest, unsigned n) {
    while (n--) {
        *dest++ = 0;
    }
}

/* Copy CODE payload from ROM to RAM, zero BSS, jump to init_relocated. */
void boot_main(void) {
    boot_copy(_code_start, _code_load, (unsigned)_code_size);
    boot_zero(_bss_start, (unsigned)_bss_size);
    init_relocated();
}

#else
/* ================================================================
 * SDCC / z88dk
 * ================================================================ */

/* Linker symbols for self-relocation.
 * C adds _ prefix; linker sees __X for extern byte _X.
 * Taking &_X gives the linker-assigned address as a pointer. */
extern byte _BOOT_tail;       /* end of BOOT section = ROM source of CODE payload */
extern const byte intvec;     /* IVT at 0x7000: start of CODE payload */
extern const byte code_end;   /* sentinel at end of CODE payload */

/* ROM entry point — must be first function in BOOT section.
 * Copies CODE payload from ROM to RAM at 0x7000, then jumps there.
 * Payload size computed at runtime — z80asm can't DEFC across subsections. */
void begin(void) {
    intrinsic_di();
    __asm__("ld sp, #" STR(ROM_STACK) "\n");
    memcpy((void *)&intvec, &_BOOT_tail, &code_end - &intvec + 1);
    init_relocated();
}

/* Functions only used before prom_disable() — placed in BOOT section
 * to fill padding between begin() and the NMI handler.
 * Called from main() in rom.c after CODE has been copied to RAM. */

/* Initialize FDC with Specify command. */
void init_fdc(void) {
    delay(2, 157);                   /* wait for FDC to become ready */
    while (fdc_status() & 0b00011111) {
        ;
    }                                /* wait until no drives are busy */
    fdc_write_when_ready(0x03);      /* Specify command */
    fdc_write_when_ready(0x4F);      /*   SRT=4 (8ms step), HUT=F (240ms unload) */
    fdc_write_when_ready(0x20);      /*   HLT=10 (32ms load), ND=0 (DMA mode) */
}

/* Banner string — raw bytes in BOOT section, referenced by
 * display_banner_and_start_crt() in CODE via extern.
 * Fills BOOT padding that would otherwise be 0xFF. */
#include "build_stamp.h"
void banner_string(void) __naked {
    __asm__("DEFM \" RC700\"\n"
            "DEFM " BUILD_STAMP_STR "\n");
}

/* Pad with 0xFF to reach 0x0066 where the Z80 NMI vector is hardwired.
 * NMI is unused on RC702; RETN restores IFF1 from IFF2 and returns. */
void pad_to_nmi_retn(void) __naked {
    __asm__("DEFS 0x0066 - ASMPC, 0xFF\n"
        "retn\n");
}

#endif
