/*
 * boot_rom.c — BOOT section code.
 *
 * Lives in ROM at ORG 0x0000, accessible until prom_disable().
 * Contains:
 *   - Entry point: self-relocate CODE payload from ROM to RAM
 *   - banner_string    Raw banner text (referenced by display_banner in CODE)
 *   - NMI handler      RETN at 0x0066
 *   - init_fdc()       FDC Specify command (SDCC only; clang has it in rom.c)
 *
 * SDCC:  compiled with --codeseg BOOT, uses z80asm section directives.
 * clang: compiled without -ffunction-sections, uses GNU as directives.
 *        Linker script places all of boot.o .text at 0x0000 in ROM.
 *
 * IMPORTANT: Code in BOOT cannot call functions in CODE (memcpy, memset,
 * delay, etc.) — the CODE payload has not been copied to RAM yet when
 * BOOT runs.  Self-relocation and BSS zeroing use inline asm.
 */

#ifdef __SDCC
#include <string.h>
#include <intrinsic.h>
#endif
#include "rom.h"

/* Post-relocation init (in rom.c, relocated to RAM) */
extern void init_relocated(void);

#if defined(__clang__) && !defined(HOST_TEST)
/* ================================================================
 * clang / llvm-z80
 * ================================================================ */

/* ROM entry point at address 0x0000.
 * File-scope asm: DI must be the very first instruction (Z80 reset vector).
 * Copies CODE from ROM to RAM, zeroes BSS, jumps to init_relocated.
 * Cannot call C library functions — they live in CODE which hasn't been copied yet. */
/* Layout must be: __start, banner, NMI@0x0066, zero_bss.
 * Rearranging breaks boot in MAME (reason unknown). */
__asm__(
    ".globl __start\n"
    "__start:\n"
    "\tdi\n"
    "\tld\tsp, " STR(ROM_STACK) "\n"
    "\tld\thl, __code_load\n"
    "\tld\tde, __code_start\n"
    "\tld\tbc, __code_size\n"
    "\tld\ta, b\n"
    "\tor\tc\n"
    "\tjr\tz, 0f\n"
    "\tldir\n"
    "0:\n"
    "\tcall\t.Lzero_bss\n"
    "\tjp\t_init_relocated\n"
);

/* Banner string — 42 raw bytes generated by Makefile.
 * Fills BOOT padding; referenced by display_banner_and_start_crt() in CODE. */
__asm__(
    ".globl _banner_string\n"
    "_banner_string:\n"
    ".incbin \"clang_z80/banner.bin\"\n"
);

/* Pad to 0x0066 for Z80 NMI vector (hardwired, unused on RC702).
 * RETN restores IFF1 from IFF2 and returns.
 * zero_bss placed after NMI (see layout comment above). */
__asm__(
    ".org 0x0066\n"
    ".globl _nmi_handler\n"
    "_nmi_handler:\n"
    "\tretn\n"
    /* Zero BSS subroutine — called from __start after LDIR copy */
    ".Lzero_bss:\n"
    "\tld\thl, __bss_start\n"
    "\tld\tbc, __bss_size\n"
    "\tld\ta, b\n"
    "\tor\tc\n"
    "\tret\tz\n"
    "\tld\t(hl), 0\n"
    "\tld\td, h\n"
    "\tld\te, l\n"
    "\tinc\tde\n"
    "\tdec\tbc\n"
    "\tld\ta, b\n"
    "\tor\tc\n"
    "\tret\tz\n"
    "\tldir\n"
    "\tret\n"
);

#else
/* ================================================================
 * SDCC / z88dk
 * ================================================================ */

/* Linker symbols for self-relocation.
 * C adds _ prefix; linker sees __X for extern byte _X.
 * Taking &_X gives the linker-assigned address as a pointer. */
extern byte _BOOT_tail;       /* end of BOOT section = ROM source of CODE payload */
extern const byte intvec;     /* IVT at 0x7000: start of CODE payload */
extern const byte code_end;   /* sentinel at end of CODE payload */

/* ROM entry point — must be first function in BOOT section.
 * Copies CODE payload from ROM to RAM at 0x7000, then jumps there.
 * Payload size computed at runtime — z80asm can't DEFC across subsections. */
void begin(void) {
    intrinsic_di();
    __asm__("ld sp, #" STR(ROM_STACK) "\n");
    memcpy((void *)&intvec, &_BOOT_tail, &code_end - &intvec + 1);
    init_relocated();
}

/* Functions only used before prom_disable() — placed in BOOT section
 * to fill padding between begin() and the NMI handler.
 * Called from main() in rom.c after CODE has been copied to RAM. */

/* Initialize FDC with Specify command. */
void init_fdc(void) {
    delay(2, 157);                   /* wait for FDC to become ready */
    while (fdc_status() & 0b00011111) {
        ;
    }                                /* wait until no drives are busy */
    fdc_write_when_ready(0x03);      /* Specify command */
    fdc_write_when_ready(0x4F);      /*   SRT=4 (8ms step), HUT=F (240ms unload) */
    fdc_write_when_ready(0x20);      /*   HLT=10 (32ms load), ND=0 (DMA mode) */
}

/* Banner string — raw bytes in BOOT section, referenced by
 * display_banner_and_start_crt() in CODE via extern.
 * Fills BOOT padding that would otherwise be 0xFF. */
#include "build_stamp.h"
void banner_string(void) __naked {
    __asm__("DEFM \" RC700\"\n"
            "DEFM " BUILD_STAMP_STR "\n");
}

/* Pad with 0xFF to reach 0x0066 where the Z80 NMI vector is hardwired.
 * NMI is unused on RC702; RETN restores IFF1 from IFF2 and returns. */
void pad_to_nmi_retn(void) __naked {
    __asm__("DEFS 0x0066 - ASMPC, 0xFF\n"
        "retn\n");
}

#endif
