#!/usr/bin/env python3
"""Generate QR code bitmap as C header for RC700 PROM semigraphic display."""

import qrcode
import sys

URL = "github.com/ravn/rc700-gensmedet"
OUTPUT = "clang/qr_data.h"

def pattern_to_charcode(pattern):
    """Convert 6-bit block pattern to ROA327 character code."""
    if pattern == 0:
        return 0x20  # space
    elif pattern < 32:
        return 0x20 + pattern
    else:
        return 0x60 + (pattern - 32)


def main():
    qr = qrcode.QRCode(
        version=2,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=1,
        border=0,
    )
    qr.add_data(URL)
    qr.make(fit=False)
    matrix = qr.modules
    size = len(matrix)
    assert size == 25, f"Expected 25x25, got {size}x{size}"

    # Pre-render as 2x2 semigraphic character codes (top+mid zones only).
    # With 6-line chars, only lines 0-5 visible: top=0-2, mid=3-5.
    # Bottom zone (lines 7-10) not visible. Bits 4,5 always 0.
    # 2x scale, 2-module quiet zone each side = 29 cols × 29 rows.
    QUIET_PX = 4  # 2 modules × 2 scale
    QR_PX = size * 2
    COLS = 29
    ROWS = 20
    screen = []

    for row in range(ROWS):
        for col in range(COLS):
            pattern = 0
            for py in range(3):
                for px in range(2):
                    pixel_y = row * 2 + py
                    pixel_x = col * 2 + px
                    if pixel_y >= QUIET_PX and pixel_x >= QUIET_PX:
                        qr_py = pixel_y - QUIET_PX
                        qr_px = pixel_x - QUIET_PX
                        if qr_py < QR_PX and qr_px < QR_PX:
                            mod_y = qr_py // 2
                            mod_x = qr_px // 2
                            if matrix[mod_y][mod_x]:
                                pattern |= 1 << (py * 2 + px)
            screen.append(pattern_to_charcode(pattern))

    # Write C header with pre-rendered screen data
    with open(OUTPUT, "w") as f:
        f.write(f"/* QR code semigraphic data for: {URL}\n")
        f.write(f" * Version 2, Error Correction L, {size}x{size} modules\n")
        f.write(f" * Pre-rendered as {COLS}x{ROWS} ROA327 character codes\n")
        f.write(f" * Generated by gen_qr.py — do not edit */\n\n")
        f.write(f"#define QR_COLS {COLS}\n")
        f.write(f"#define QR_ROWS {ROWS}\n\n")
        f.write(f"static const byte qr_screen[{len(screen)}] = {{\n")
        for r in range(ROWS):
            row_data = screen[r * COLS:(r + 1) * COLS]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in row_data))
            if r < ROWS - 1:
                f.write(",")
            f.write("\n")
        f.write("};\n")

    print(f"Generated {OUTPUT}: {COLS}x{ROWS} screen, {len(screen)} bytes, URL={URL}")

    # Print ASCII preview
    print()
    for row in matrix:
        print("".join("\u2588\u2588" if col else "  " for col in row))

if __name__ == "__main__":
    main()
