; boot.s — BOOT section for RC700 autoload PROM (clang/llvm-z80)
;
; Lives in ROM at 0x0000, accessible until prom_disable().
; Contains:
;   - _start        ROM entry point: set SP, copy CODE to RAM, jump
;   - _init_fdc     FDC Specify command (called from main)
;   - banner_string Raw banner text (42 bytes)
;   - NMI handler   RETN at 0x0066

	.text
	.globl	__start

; ROM entry point at address 0x0000
__start:
	di
	ld	sp, 0xBFFF

	; Copy CODE payload from ROM (after BOOT) to RAM at 0x7300
	; Source: __code_load (LMA, right after BOOT in ROM)
	; Dest:   __code_start (VMA = 0x7300)
	; Length: __code_size
	ld	hl, __code_load
	ld	de, __code_start
	ld	bc, __code_size
	ld	a, b
	or	c
	jr	z, .Lcopy_done
	ldir
.Lcopy_done:
	; Zero BSS then jump to relocated code
	call	.Lzero_bss
	jp	_init_relocated

	; init_fdc is now in rom.c (C code, runs after relocation)

	; banner_string is defined in the Makefile via -DBUILD_STAMP
	; and assembled from a generated .s file. See Makefile clang target.
	.globl	_banner_string
_banner_string:
	.incbin	"clang_z80/banner.bin"
	; 42 bytes (BANNER_LENGTH) — generated by Makefile

	; Pad with 0xFF to NMI vector at 0x0066
	; The assembler can't compute padding at assemble time,
	; so the linker script must ensure NMI lands at 0x0066.

	.org	0x0066
	.globl	_nmi_handler
_nmi_handler:
	retn

; BSS zero routine — called from _start after LDIR copy
.Lzero_bss:
	ld	hl, __bss_start
	ld	bc, __bss_size
	ld	a, b
	or	c
	ret	z
	ld	(hl), 0
	ld	d, h
	ld	e, l
	inc	de
	dec	bc
	ld	a, b
	or	c
	ret	z
	ldir
	ret
